# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'win.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(860, 757)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 831, 117))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(10, 20, 10, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.path_input = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.path_input.setFont(font)
        self.path_input.setObjectName("path_input")
        self.horizontalLayout.addWidget(self.path_input)
        self.open_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.open_button.setFont(font)
        self.open_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open_button.setMouseTracking(True)
        self.open_button.setObjectName("open_button")
        self.horizontalLayout.addWidget(self.open_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 312, 831, 121))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.col_info_container = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.col_info_container.setContentsMargins(10, 20, 10, 20)
        self.col_info_container.setObjectName("col_info_container")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.pub_title_input = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pub_title_input.setFont(font)
        self.pub_title_input.setObjectName("pub_title_input")
        self.horizontalLayout_2.addWidget(self.pub_title_input)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lib_title_input = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lib_title_input.setFont(font)
        self.lib_title_input.setObjectName("lib_title_input")
        self.horizontalLayout_2.addWidget(self.lib_title_input)
        self.col_info_container.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.pub_id_input = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pub_id_input.setFont(font)
        self.pub_id_input.setObjectName("pub_id_input")
        self.horizontalLayout_9.addWidget(self.pub_id_input)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_9.addWidget(self.label_12)
        self.lib_id_input = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lib_id_input.setFont(font)
        self.lib_id_input.setObjectName("lib_id_input")
        self.horizontalLayout_9.addWidget(self.lib_id_input)
        self.col_info_container.addLayout(self.horizontalLayout_9)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 490, 831, 150))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.options_container = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.options_container.setContentsMargins(10, 20, 10, 20)
        self.options_container.setObjectName("options_container")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.letter_only_button = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.letter_only_button.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.letter_only_button.setFont(font)
        self.letter_only_button.setAcceptDrops(False)
        self.letter_only_button.setObjectName("letter_only_button")
        self.horizontalLayout_4.addWidget(self.letter_only_button)
        self.no_space_button = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.no_space_button.setFont(font)
        self.no_space_button.setObjectName("no_space_button")
        self.horizontalLayout_4.addWidget(self.no_space_button)
        self.strict_button = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.strict_button.setFont(font)
        self.strict_button.setObjectName("strict_button")
        self.horizontalLayout_4.addWidget(self.strict_button)
        self.options_container.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(20)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.options_container.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(20)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.correct_color_box = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.correct_color_box.setFont(font)
        self.correct_color_box.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.correct_color_box.setObjectName("correct_color_box")
        self.horizontalLayout_5.addWidget(self.correct_color_box)
        self.ambiguous_color_box = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ambiguous_color_box.setFont(font)
        self.ambiguous_color_box.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ambiguous_color_box.setObjectName("ambiguous_color_box")
        self.horizontalLayout_5.addWidget(self.ambiguous_color_box)
        self.wrong_color_box = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.wrong_color_box.setFont(font)
        self.wrong_color_box.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.wrong_color_box.setEditable(False)
        self.wrong_color_box.setCurrentText("")
        self.wrong_color_box.setObjectName("wrong_color_box")
        self.horizontalLayout_5.addWidget(self.wrong_color_box)
        self.options_container.addLayout(self.horizontalLayout_5)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(20, 650, 155, 51))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.start_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.start_button.setFont(font)
        self.start_button.setObjectName("start_button")
        self.horizontalLayout_8.addWidget(self.start_button)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(20, 211, 831, 106))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.sheet_name_container = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.sheet_name_container.setContentsMargins(10, 20, 10, 20)
        self.sheet_name_container.setObjectName("sheet_name_container")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.sheet_name_container.addWidget(self.label_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.sheet_name_input = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.sheet_name_input.setFont(font)
        self.sheet_name_input.setObjectName("sheet_name_input")
        self.horizontalLayout_10.addWidget(self.sheet_name_input)
        self.sheet_name_container.addLayout(self.horizontalLayout_10)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 170, 256, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.use_user_enter_button = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.use_user_enter_button.setFont(font)
        self.use_user_enter_button.setObjectName("use_user_enter_button")
        self.horizontalLayout_6.addWidget(self.use_user_enter_button)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 130, 256, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.use_id_button = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.use_id_button.setFont(font)
        self.use_id_button.setAcceptDrops(False)
        self.use_id_button.setChecked(True)
        self.use_id_button.setObjectName("use_id_button")
        self.horizontalLayout_11.addWidget(self.use_id_button)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 440, 831, 43))
        self.layoutWidget.setObjectName("layoutWidget")
        self.end_row_container = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.end_row_container.setContentsMargins(10, 0, 10, 0)
        self.end_row_container.setObjectName("end_row_container")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.end_row_container.addWidget(self.label_10)
        self.pub_end_row = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pub_end_row.setFont(font)
        self.pub_end_row.setObjectName("pub_end_row")
        self.end_row_container.addWidget(self.pub_end_row)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.end_row_container.addWidget(self.label_11)
        self.lib_end_row = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lib_end_row.setFont(font)
        self.lib_end_row.setObjectName("lib_end_row")
        self.end_row_container.addWidget(self.lib_end_row)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 860, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Comparer"))
        self.label.setText(_translate("MainWindow", "File Path:"))
        self.open_button.setText(_translate("MainWindow", "Open..."))
        self.label_3.setText(_translate("MainWindow", "Pub Title Col (A-Z):"))
        self.pub_title_input.setText(_translate("MainWindow", "A"))
        self.label_2.setText(_translate("MainWindow", "Lib Title Col (A-Z):"))
        self.lib_title_input.setText(_translate("MainWindow", "C"))
        self.label_8.setText(_translate("MainWindow", "Pub ID Col (A-Z):"))
        self.pub_id_input.setText(_translate("MainWindow", "B"))
        self.label_12.setText(_translate("MainWindow", "Lib Id Col (A-Z):"))
        self.lib_id_input.setText(_translate("MainWindow", "D"))
        self.letter_only_button.setText(_translate("MainWindow", "no weird letters"))
        self.no_space_button.setText(_translate("MainWindow", "No Spaces"))
        self.strict_button.setText(_translate("MainWindow", "Strict Compare"))
        self.label_4.setText(_translate("MainWindow", "Correct Color"))
        self.label_6.setText(_translate("MainWindow", "Ambiguous Color"))
        self.label_5.setText(_translate("MainWindow", "Wrong Color"))
        self.label_7.setText(_translate("MainWindow", "Start:"))
        self.start_button.setText(_translate("MainWindow", "Fire!"))
        self.label_9.setText(_translate("MainWindow", "Sheet Name:"))
        self.sheet_name_input.setText(_translate("MainWindow", "Data"))
        self.use_user_enter_button.setText(_translate("MainWindow", "Use User Entered Data"))
        self.use_id_button.setText(_translate("MainWindow", "Use ID Compare"))
        self.label_10.setText(_translate("MainWindow", "Pub End Row (number):"))
        self.pub_end_row.setText(_translate("MainWindow", "?"))
        self.label_11.setText(_translate("MainWindow", "Lib End Row (number):"))
        self.lib_end_row.setText(_translate("MainWindow", "?"))
